# ============================================================================
# REQUIRED HELPER ENTITIES
# ============================================================================
# Add these to your configuration.yaml or create via UI:
# Settings > Devices & Services > Helpers > Create Helper > Toggle

input_boolean:
  solar_curtailment_active:
    name: Solar Curtailment Active
    icon: mdi:solar-power-variant
  
  fronius_manual_override:
    name: Fronius Manual Override
    icon: mdi:toggle-switch-off-outline

# ============================================================================
# COMPANION AUTOMATIONS
# ============================================================================
# These work alongside the main blueprint automation

automation:
  # === AUTO-RESTORE AT END TIME ===
  - id: fronius_curtailment_auto_restore
    alias: Fronius - Auto Restore at 4pm
    description: Automatically restore full solar power at the configured end time
    mode: single
    
    trigger:
      - platform: time
        at: input_datetime.curtailment_end_time  # Or hardcode: "16:00:00"
    
    condition:
      - condition: state
        entity_id: input_boolean.solar_curtailment_active
        state: "on"
    
    action:
      - service: input_boolean.turn_off
        target:
          entity_id: input_boolean.solar_curtailment_active
      
      # NOTE: The main blueprint automation will handle the Modbus write
      # when curtailment_active turns off and price is positive

  # === MANUAL OVERRIDE HANDLER ===
  - id: fronius_manual_override_handler
    alias: Fronius - Manual Override Force Full Power
    description: Emergency override to immediately restore full power
    mode: single
    
    trigger:
      - platform: state
        entity_id: input_boolean.fronius_manual_override
        to: "on"
    
    action:
      - service: input_boolean.turn_off
        target:
          entity_id: input_boolean.solar_curtailment_active
      
      # Write full power to Fronius
      # NOTE: Adjust these values based on your blueprint configuration
      - service: modbus.write_register
        data:
          hub: mb_fronius_control  # CHANGE THIS to your hub name
          unit: 1  # CHANGE THIS to your unit ID
          address: 40232  # CHANGE THIS to your register address
          value:
            - 8200  # CHANGE THIS to your inverter max output
            - 0
            - 0
            - 0
            - 1  # Disable limit

  # === AUTO-RESET MANUAL OVERRIDE ===
  - id: fronius_manual_override_auto_reset
    alias: Fronius - Reset Manual Override at 6am
    description: Automatically turn off manual override each morning
    mode: single
    
    trigger:
      - platform: time
        at: "06:00:00"  # Or use input_datetime helper
    
    condition:
      - condition: state
        entity_id: input_boolean.fronius_manual_override
        state: "on"
    
    action:
      - service: input_boolean.turn_off
        target:
          entity_id: input_boolean.fronius_manual_override
