blueprint:
  name: Fronius Solar Curtailment - Dynamic Price Control
  description: >
    Automatically throttles Fronius inverter during negative grid prices to prevent
    exporting power while maintaining battery charging and house load. Includes
    manual override and automatic restoration at 4pm and 6am.
    
    **Requirements:**
    - Fronius inverter with Modbus TCP enabled
    - Modbus integration configured (see modbus config section)
    - Input boolean helpers (auto-created if using UI)
    - Grid price sensor with negative values during low-price periods
    - Inverter sensors for battery level, load power, and export power
  
  domain: automation
  
  input:
    # --- Modbus Configuration ---
    modbus_hub:
      name: Modbus Hub Name
      description: Name of your Modbus hub (from modbus configuration)
      default: mb_fronius_control
      selector:
        text:
    
    modbus_unit_id:
      name: Modbus Unit ID
      description: Modbus unit ID for your Fronius inverter (usually 1)
      default: 1
      selector:
        number:
          min: 1
          max: 247
          mode: box
    
    # --- Inverter Specifications ---
    inverter_max_power:
      name: Inverter Maximum Power (W)
      description: Maximum power output of your Fronius inverter in Watts
      default: 8200
      selector:
        number:
          min: 1000
          max: 30000
          step: 100
          unit_of_measurement: W
          mode: box
    
    battery_charge_rate:
      name: Battery Charge Rate (W)
      description: Desired battery charging power during curtailment in Watts
      default: 4500
      selector:
        number:
          min: 0
          max: 15000
          step: 100
          unit_of_measurement: W
          mode: box
    
    safety_buffer:
      name: Safety Buffer (W)
      description: Additional power buffer to prevent grid export fluctuations
      default: 500
      selector:
        number:
          min: 0
          max: 2000
          step: 50
          unit_of_measurement: W
          mode: box
    
    minimum_generation:
      name: Minimum Generation (W)
      description: Minimum power the inverter should generate during curtailment
      default: 500
      selector:
        number:
          min: 0
          max: 5000
          step: 100
          unit_of_measurement: W
          mode: box
    
    # --- Sensor Entities ---
    grid_price_sensor:
      name: Grid Sell Price Sensor
      description: Sensor showing current grid sell price (negative during curtailment periods)
      selector:
        entity:
          domain: sensor
    
    battery_level_sensor:
      name: Battery Level Sensor
      description: Sensor showing battery state of charge percentage
      selector:
        entity:
          domain: sensor
    
    load_power_sensor:
      name: House Load Power Sensor
      description: Sensor showing current house power consumption in Watts
      selector:
        entity:
          domain: sensor
    
    export_power_sensor:
      name: Export Power Sensor
      description: Sensor showing current grid export power in Watts
      selector:
        entity:
          domain: sensor
    
    # --- Helper Entities ---
    curtailment_active_switch:
      name: Curtailment Active Switch
      description: Input boolean to track curtailment state (will be created if it doesn't exist)
      default: input_boolean.solar_curtailment_active
      selector:
        entity:
          domain: input_boolean
    
    manual_override_switch:
      name: Manual Override Switch
      description: Input boolean for emergency manual override (will be created if it doesn't exist)
      default: input_boolean.fronius_manual_override
      selector:
        entity:
          domain: input_boolean
    
    # --- Time Settings ---
    curtailment_end_time:
      name: Curtailment End Time
      description: Time to automatically disable curtailment each day
      default: "16:00:00"
      selector:
        time:
    
    daily_reset_time:
      name: Daily Reset Time
      description: Time to reset inverter to full power each morning
      default: "06:00:00"
      selector:
        time:
    
    update_interval:
      name: Update Interval (minutes)
      description: How often to check and update curtailment (in minutes)
      default: 5
      selector:
        number:
          min: 1
          max: 30
          step: 1
          unit_of_measurement: min
          mode: slider

mode: restart
max: 10
max_exceeded: silent

variables:
  inverter_max: !input inverter_max_power
  battery_charge: !input battery_charge_rate
  buffer: !input safety_buffer
  min_gen: !input minimum_generation

trigger:
  - platform: state
    entity_id: !input battery_level_sensor
  - platform: state
    entity_id: !input grid_price_sensor
  - platform: state
    entity_id: !input load_power_sensor
  - platform: state
    entity_id: !input export_power_sensor
  - platform: event
    event_type: homeassistant_start
  - platform: time_pattern
    minutes: !input update_interval

condition:
  - condition: time
    before: !input curtailment_end_time
  - condition: state
    entity_id: !input manual_override_switch
    state: "off"

action:
  - choose:
      # --- CHOICE 1: CURTAILMENT ACTIVATION (NEGATIVE PRICE, NOT YET ACTIVE) ---
      - conditions:
          - condition: numeric_state
            entity_id: !input grid_price_sensor
            below: 0
          - condition: state
            entity_id: !input curtailment_active_switch
            state: "off"
        sequence:
          - variables:
              house_load: "{{ states(!input load_power_sensor) | int(0) }}"
              target_generation: "{{ house_load + battery_charge + buffer }}"
              watt_limit: "{{ [[target_generation, min_gen] | max, inverter_max] | min }}"
              sunspec_power_limit: "{{ (watt_limit * 10000 / inverter_max) | int(0) }}"
          
          - service: input_boolean.turn_on
            target:
              entity_id: !input curtailment_active_switch
          
          - service: modbus.write_register
            data:
              hub: !input modbus_hub
              unit: !input modbus_unit_id
              address: 40232
              value:
                - "{{ sunspec_power_limit }}"
                - 0
                - 0
                - 0
                - 0  # WMaxLim_Ena: 0 to ENABLE the limit

      # --- CHOICE 2: MAINTAIN/UPDATE CURTAILMENT (NEGATIVE PRICE, ALREADY ACTIVE) ---
      - conditions:
          - condition: numeric_state
            entity_id: !input grid_price_sensor
            below: 0
          - condition: state
            entity_id: !input curtailment_active_switch
            state: "on"
        sequence:
          - variables:
              house_load: "{{ states(!input load_power_sensor) | int(0) }}"
              target_generation: "{{ house_load + battery_charge + buffer }}"
              watt_limit: "{{ [[target_generation, min_gen] | max, inverter_max] | min }}"
              sunspec_power_limit: "{{ (watt_limit * 10000 / inverter_max) | int(0) }}"
          
          - service: modbus.write_register
            data:
              hub: !input modbus_hub
              unit: !input modbus_unit_id
              address: 40232
              value:
                - "{{ sunspec_power_limit }}"
                - 0
                - 0
                - 0
                - 0  # WMaxLim_Ena: 0 to keep limit enabled

      # --- CHOICE 3: CURTAILMENT DEACTIVATION (POSITIVE/ZERO PRICE, CURRENTLY ACTIVE) ---
      - conditions:
          - condition: not
            conditions:
              - condition: numeric_state
                entity_id: !input grid_price_sensor
                below: 0
          - condition: state
            entity_id: !input curtailment_active_switch
            state: "on"
        sequence:
          - service: input_boolean.turn_off
            target:
              entity_id: !input curtailment_active_switch
          
          - service: modbus.write_register
            data:
              hub: !input modbus_hub
              unit: !input modbus_unit_id
              address: 40232
              value:
                - "{{ inverter_max }}"  # WMaxLim_W: Set to max power
                - 0                      # WMaxLim_W_SF
                - 0                      # Reserved
                - 0                      # Reserved
                - 1                      # WMaxLim_Ena: 1 to DISABLE the limit

    # --- DEFAULT: NO ACTION NEEDED (POSITIVE PRICE, ALREADY OFF) ---
    default: []

---
# Additional automation for 4pm restoration
blueprint:
  name: Fronius Solar Curtailment - 4PM Restoration
  description: >
    Companion automation to restore Fronius to full power at the specified time
    (default 4pm). This should be imported along with the main curtailment blueprint.
  
  domain: automation
  
  input:
    modbus_hub:
      name: Modbus Hub Name
      description: Name of your Modbus hub (must match main automation)
      default: mb_fronius_control
      selector:
        text:
    
    modbus_unit_id:
      name: Modbus Unit ID
      description: Modbus unit ID for your Fronius inverter (usually 1)
      default: 1
      selector:
        number:
          min: 1
          max: 247
          mode: box
    
    inverter_max_power:
      name: Inverter Maximum Power (W)
      description: Maximum power output of your Fronius inverter in Watts (must match main automation)
      default: 8200
      selector:
        number:
          min: 1000
          max: 30000
          step: 100
          unit_of_measurement: W
          mode: box
    
    curtailment_active_switch:
      name: Curtailment Active Switch
      description: Input boolean to track curtailment state (must match main automation)
      default: input_boolean.solar_curtailment_active
      selector:
        entity:
          domain: input_boolean
    
    restoration_time:
      name: Restoration Time
      description: Time to automatically restore full power each day
      default: "16:00:00"
      selector:
        time:

mode: single

trigger:
  - platform: time
    at: !input restoration_time

condition:
  - condition: state
    entity_id: !input curtailment_active_switch
    state: "on"

action:
  - service: input_boolean.turn_off
    target:
      entity_id: !input curtailment_active_switch
  
  - service: modbus.write_register
    data:
      hub: !input modbus_hub
      unit: !input modbus_unit_id
      address: 40232
      value:
        - !input inverter_max_power  # WMaxLim_W: Set to max power
        - 0                           # WMaxLim_W_SF
        - 0                           # Reserved
        - 0                           # Reserved
        - 1                           # WMaxLim_Ena: 1 to DISABLE the limit

---
# Additional automation for manual override
blueprint:
  name: Fronius Solar Curtailment - Manual Override
  description: >
    Emergency override to immediately restore Fronius to full power when
    the manual override switch is activated.
  
  domain: automation
  
  input:
    modbus_hub:
      name: Modbus Hub Name
      description: Name of your Modbus hub (must match main automation)
      default: mb_fronius_control
      selector:
        text:
    
    modbus_unit_id:
      name: Modbus Unit ID
      description: Modbus unit ID for your Fronius inverter (usually 1)
      default: 1
      selector:
        number:
          min: 1
          max: 247
          mode: box
    
    inverter_max_power:
      name: Inverter Maximum Power (W)
      description: Maximum power output of your Fronius inverter in Watts (must match main automation)
      default: 8200
      selector:
        number:
          min: 1000
          max: 30000
          step: 100
          unit_of_measurement: W
          mode: box
    
    curtailment_active_switch:
      name: Curtailment Active Switch
      description: Input boolean to track curtailment state (must match main automation)
      default: input_boolean.solar_curtailment_active
      selector:
        entity:
          domain: input_boolean
    
    manual_override_switch:
      name: Manual Override Switch
      description: Input boolean for emergency manual override (must match main automation)
      default: input_boolean.fronius_manual_override
      selector:
        entity:
          domain: input_boolean

trigger:
  - platform: state
    entity_id: !input manual_override_switch
    to: "on"

action:
  - service: input_boolean.turn_off
    target:
      entity_id: !input curtailment_active_switch
  
  - service: modbus.write_register
    data:
      hub: !input modbus_hub
      unit: !input modbus_unit_id
      address: 40232
      value:
        - !input inverter_max_power  # WMaxLim_W: Set to max power
        - 0                           # WMaxLim_W_SF
        - 0                           # Reserved
        - 0                           # Reserved
        - 1                           # WMaxLim_Ena: 1 to DISABLE the limit

---
# Additional automation for morning reset
blueprint:
  name: Fronius Solar Curtailment - Morning Reset
  description: >
    Reset Fronius to full power each morning to prepare for the day.
  
  domain: automation
  
  input:
    modbus_hub:
      name: Modbus Hub Name
      description: Name of your Modbus hub (must match main automation)
      default: mb_fronius_control
      selector:
        text:
    
    modbus_unit_id:
      name: Modbus Unit ID
      description: Modbus unit ID for your Fronius inverter (usually 1)
      default: 1
      selector:
        number:
          min: 1
          max: 247
          mode: box
    
    inverter_max_power:
      name: Inverter Maximum Power (W)
      description: Maximum power output of your Fronius inverter in Watts (must match main automation)
      default: 8200
      selector:
        number:
          min: 1000
          max: 30000
          step: 100
          unit_of_measurement: W
          mode: box
    
    curtailment_active_switch:
      name: Curtailment Active Switch
      description: Input boolean to track curtailment state (must match main automation)
      default: input_boolean.solar_curtailment_active
      selector:
        entity:
          domain: input_boolean
    
    reset_time:
      name: Morning Reset Time
      description: Time to reset inverter each morning
      default: "06:00:00"
      selector:
        time:

mode: single

trigger:
  - platform: time
    at: !input reset_time

action:
  - service: input_boolean.turn_off
    target:
      entity_id: !input curtailment_active_switch
  
  - service: modbus.write_register
    data:
      hub: !input modbus_hub
      unit: !input modbus_unit_id
      address: 40232
      value:
        - !input inverter_max_power  # WMaxLim_W: Set to max power
        - 0                           # WMaxLim_W_SF
        - 0                           # Reserved
        - 0                           # Reserved
        - 1                           # WMaxLim_Ena: 1 to DISABLE the limit

